apiVersion: apps/v1
kind: Deployment
metadata:
  name: yourls
  labels: 
    app: yourls-front
spec:
  replicas: 3
  selector:
    matchLabels:
      app: yourls-front
  template:
    metadata:
      labels:
        app: yourls-front
    spec:
      containers:
      - name: yourls
        image: yourls:1.7.4-apache
        env:
        - name: YOURLS_DB_HOST
          value: "mysql.default.svc.cluster.local"
        - name: YOURLS_DB_PASS
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: YOURLS_DB_USER
          valueFrom:
            secretKeyRef:
              name: yourls-secret
              key: dbuser
        - name: YOURLS_SITE
          value: "https://short.zylowski.net"
        - name: YOURLS_USER
          valueFrom:
            secretKeyRef:
              name: yourls-secret
              key: yourlsuser
        - name: YOURLS_PASS
          valueFrom:
            secretKeyRef:
              name: yourls-secret
              key: yourlspassword
        ports:
        - containerPort: 80
          name: yourls-port
