apiVersion: v1
kind: Pod
metadata:
  name: database
spec:
  containers:
  - name: db
    image: mysql
    volumeMounts:
    - name: dbconnection
      mountPath: "/root/dbcredentials"
      readOnly: true
    env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: db-secret
            key: pass
  volumes:
  - name: dbconnection
    secret:
      secretName: db-secret
