apiVersion: v1
kind: Pod
metadata:
  name: logs-learning
spec:
  containers:
  - name: ubuntu
    image: ubuntu:18.04
    command: [ "sleep", "inf" ]
  - name: nginx
    image: nginx
    ports:
      - containerPort: 80
