apiVersion: batch/v1
kind: Job
metadata:
  name: downloader-ttl
spec:
  ttlSecondsAfterFinished: 10
  template:
    spec:
      containers:
      - name: yt-downloader
        image: wernight/youtube-dl
        command: ["youtube-dl", "https://www.youtube.com/watch?v=pHwt5oC7_lQ"]
      restartPolicy: Never
