apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: yaml
  name: httpd-dep
  labels:
    app: httpd-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: httpd-app
  template:
    metadata:
      labels:
        app: httpd-app
    spec:
      containers:
      - name: httpd
        image: httpd
        ports:
        - containerPort: 80
