apiVersion: v1
kind: Pod
metadata:
  name: security-2
spec:
  containers:
  - name: ubuntu
    image: ubuntu:18.04
    command: [ "sleep", "inf" ]
    securityContext:
      capabilities:
        add: [ "NET_ADMIN" ]
